# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4f3b4e515518414a601e1903dfd7d44d668d2142d8ae7fb95d560f0c2939bfb84fc991a65924a9f50ab5c0dbbfec4000ddc5bf53a0c1a8d5cb5a6f35747c11c

test:
  secret_key_base: fd3fa58f5e198bec70d69c2daa35c31d78cdd7a23ffaaa9f615e2c24c999318f8259f324dfc0a2eea2a18be8b9ace5625ff16150c517c99fe06ddc2275e74fa2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
